
spring:
  application:
    name: jbillcore
  datasource:
    url: jdbc:postgresql://localhost:5432/jbillcore
    username: jbillcore
    password: jbillcore
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true